// End-to-end decode smoke against an assembled nodejs-target package (#37 stretch).
//
// Imports the package the way a consumer would, decodes a golden wire buffer
// (generated by the native `justerm::encode`), builds a palette, and resolves a
// known cell's colour — proving the published decode path produces correct pixels
// for a real frame, not just that the modules import. Exits non-zero on failure.
//
// Usage: `node scripts/smoke-decode.mjs <nodejs-pkg-dir> <golden-file>`
import { createRequire } from "node:module";
import { readFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

const pkgDir = resolve(process.argv[2] ?? "");
const goldenPath = resolve(process.argv[3] ?? "");
if (!process.argv[2] || !process.argv[3]) {
  console.error("usage: smoke-decode.mjs <nodejs-pkg-dir> <golden-file>");
  process.exit(1);
}

function fail(msg) {
  console.error(`smoke-decode FAIL: ${msg}`);
  process.exit(1);
}

// nodejs target is CommonJS; the colour helpers are ESM.
const require = createRequire(import.meta.url);
const wasm = require(join(pkgDir, "justerm_wasm.js"));
const colors = await import(pathToFileURL(join(pkgDir, "colors.js")));

const bytes = new Uint8Array(readFileSync(goldenPath));
const frame = wasm.decodeFrame(bytes);

if (frame.codepoints[0] !== "A".codePointAt(0)) {
  fail(`codepoints[0] = ${frame.codepoints[0]}, expected 'A'`);
}

// Default ANSI (unused here); index 196 comes from the xterm cube.
const palette = {
  colors: wasm.buildPalette(new Uint32Array(16)),
  defaultFg: 0x000000,
  defaultBg: 0x000000,
};
const fgRgb = colors.resolveRgb(frame.fg[0], palette, colors.FG);
if (fgRgb !== 0xff0000) {
  fail(`resolveRgb(fg[0]) = 0x${fgRgb.toString(16)}, expected 0xff0000 (Indexed 196)`);
}

frame.free();
console.log("smoke-decode OK: golden frame decoded, fg[0] -> 0xff0000");
